on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      uses: DamianReeves/write-file-action
      with:
        path: addons.json
        contents: |
          echo ${{ steps.hello.outputs.addons }}"
        write-mode: overwrite
