on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch CurseForge addons
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: |
        addons=$(./curse.sh)
        echo $addons > catalog.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add catalog.json
        git commit -m "chore: updated catalog"
        git push
