on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch CurseForge addons
    steps:
    - uses: actions/checkout@v2
    - name: Bash
      run: |
        index=0
        page_size=500
        number_of_addons=$page_size
        addons=[]
        while [ $number_of_addons == $page_size ]
        do
          curse_endpoint="https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=1&pageSize=${page_size}&index=${index}"
          data=$(curl -s $curse_endpoint)
          number_of_addons=$(echo "$data" | jq '. | length')
          echo $(echo "$data" | jq 'map({"id": .id, "name": .name, "summary": .summary, "numberOfDownloads": .downloadCount, "categories": [.categories[] | .name], "source": "curse" })') > new.json
          addons=$(echo $addons | jq --argfile n new.json '. + $n')
          index=$(( $index + $page_size ))
        done
        addons > catalog.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated catalog"
        git push
