on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./action.yml
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get addons
      run: echo "${{ steps.hello.outputs.addons }}"
