on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch CurseForge addons
    steps:
    - uses: actions/checkout@v2
    - name: Bash
      run: |
        echo "some data for the file" > catalog.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated catalog"
        git push
