on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch addon data
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: |
        ./curse.sh curse.json
        ./tukui.sh tukui.json
        ./wowi.sh wowi.json
        jq -c -s '.[0] + .[1]' wowi.json tukui.json curse.json > catalog.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add catalog.json curse.json tukui.json
        git commit -m "chore: updated catalog"
        git push
