on: 
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch CurseForge addons
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: |
        ./curse.sh curse.json
        ./tukui.sh tukui.json
        jq -s '.[0] + .[1]' tukui.json curse.json > catalog.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add catalog.json curse.json tukui.json
        git commit -m "chore: updated catalog"
        git push
